/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Logo.glb 
*/

import React from 'react'
import * as THREE from 'three';
import { useFrame } from "@react-three/fiber";
import fragmentShader from './shaders/fragment.glsl.js';
import circleShader from './shaders/circleFragments.glsl.js';

const BgPlane = () => {

  const uniforms = {
    iTime: { value: 0 },
    iResolution:  { value: new THREE.Vector3() },
  };

  const shaderMaterial = new THREE.ShaderMaterial({
    fragmentShader: fragmentShader,
    uniforms: uniforms,
  });

  const circleShaderMaterial = new THREE.ShaderMaterial({
    fragmentShader: circleShader,
    uniforms: uniforms,
  });
  // materials['SVGMat.002']

  useFrame(() => {
    uniforms.iTime.value += 0.01;

    const canvas = document.getElementById('LogoCanvas');
    uniforms.iResolution.value.set(canvas.clientWidth, canvas.clientHeight, 1);
  });

  return (
    <mesh position={[0, 0, -1]} rotation={[0, 0, 0]} material={circleShaderMaterial}>
        <planeGeometry args={[5, 5]} />
    </mesh>
  )
}

export default BgPlane;