/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Logo.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'
import * as THREE from 'three';
import fragementShader from './shaders/fragment.glsl';

export function Logo(props) {
  const shaderMaterial = new THREE.ShaderMaterial({
    fragmentShader: fragementShader
  });
  // materials['SVGMat.002']

  const { nodes, materials } = useGLTF('/models/mine/Logo.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve001.geometry} material={shaderMaterial} position={[-0.5, -0.75, 0]} rotation={[Math.PI / 2, 0, 0]} />
      <mesh geometry={nodes.Curve002.geometry} material={materials['SVGMat.003']} position={[-0.5, -0.75, 0]} rotation={[Math.PI / 2, 0, 0]} />
    </group>
  )
}

useGLTF.preload('/models/mine/Logo.glb')
