/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Logo.glb 
*/

import { useGLTF } from "@react-three/drei";
import { useRef } from "react";

export function Logo(props) {
  const meshRef = useRef();

  // const uniforms = {
  //   iTime: { value: 0 },
  //   iResolution: { value: new THREE.Vector3() },
  // };

  // useFrame(() => {
  //   uniforms.iTime.value += 0.01;

  //   if (meshRef.current) {
  //     const positionOffset = Math.sin(uniforms.iTime.value * 2) * 0.002;
  //     //Hovering in the air
  //     meshRef.current.position.y += positionOffset;
  //   }
  // });

  const { nodes, materials } = useGLTF("/models/Logo.glb");
  return (
    <group {...props} dispose={null} ref={meshRef}>
      <mesh
        geometry={nodes.Curve001.geometry}
        material={materials["SVGMat.002"]}
        position={[-0.8, -0.75, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
      <mesh
        geometry={nodes.Curve002.geometry}
        material={materials["SVGMat.003"]}
        position={[-0.8, -0.75, 0]}
        rotation={[Math.PI / 2, 0, 0]}
      />
    </group>
  );
}

useGLTF.preload("/models/Logo.glb");
