/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 Logo.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Logo.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Curve001.geometry} material={materials['SVGMat.002']} />
      <mesh geometry={nodes.Curve002.geometry} material={materials['SVGMat.003']} />
    </group>
  )
}

useGLTF.preload('/Logo.glb')
